### ISSUE TITLE
UFO collide and jump

### ISSUE THREAD

**Issue by emeraldvision** [dummey/CS50-Cohort-Project-Redux#16] opened 2015-08-13 00:30 UTC

**Comment by dummey** [comment] 2015-08-13 04:49
430f761c355485191e251986a0a3f863cc3c073a changes it so that baby ufos will chase after mothers with high velocity. Can't reproduce jumping bug.

**Comment by jbtule** [comment] 2015-08-13 11:56
The big may have been fixed in commit 2b44e32

**Closed as completed** 2015-08-14 04:04 UTC
Labels: bug
